name: cron_import_questions_from_notion

# Controls when the action will run. 
on:
  schedule:
    # Every 12 hours (2 times a day)
    - cron: '0 */12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  import_questions_from_notion:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X "GET" "${{ secrets.BACKEND_URL }}/actions/import-questions-from-notion?token=${{ secrets.CRON_GITHUB_ACTION_SECRET }}"
